version: "3"
services:
  mkdocs:
    build: ./mkdocs
    image: docstool
    volumes:
      - "./data:/mkdocs/data"
      - "./mkdocs:/mkdocs"
    environment:
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DOCS_TOOL: ${DOCS_TOOL}
      DOCS_REPO: ${DOCS_REPO}
