site_name: Magestore Docs
site_dir: /mkdocs/app/site
site_url: https://docs.magestore.com
repo_url: https://github.com/Magestore/Docs
repo_name: 'GitHub'
site_description: 'Magestore Documents'
site_author: mrthinlt@gmail.com
copyright: Magestore.com
google_analytics: null
site_favicon: img/favicon.ico
#theme: readthedocs
theme_dir: 'mytheme'
extra_css:
    - css/extra.css
extra_javascript: []
extra:
    version: 1.0
